name: Generate Contribution Snake

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  update-snake:
    name: Update GitHub Contribution Snake
    runs-on: ubuntu-latest
    steps:
      # Generate the snake animation using the Platane/snk action
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: WanderingWalnut  # Replace with your GitHub username if different
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Deploy the generated SVG to the "output" branch using crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
